#!/bin/bash

echo "🖥️  GITHUB DESKTOP SETUP - PERFECT WORKFLOW"
echo "==========================================="
echo ""
echo "📋 This will create the perfect workflow where:"
echo "   ✅ I update code in this folder"
echo "   ✅ You copy to GitHub Desktop folder"
echo "   ✅ You push with one click"
echo ""

DESKTOP_FOLDER="/Users/davidniewiadomski/github-desktop-owners-cockpit"

echo "🎯 Setting up GitHub Desktop workflow..."
echo ""
echo "Step 1: Download GitHub Desktop"
echo "   📥 Go to: https://desktop.github.com"
echo "   🔐 Sign in with your GitHub account"
echo "   📂 Clone: DavidNiewiadomski/owners-cockpit"
echo "   📍 Location: $DESKTOP_FOLDER"
echo ""
echo "Step 2: Copy Function (run this after I make updates)"
echo ""
echo "copy_to_github_desktop() {"
echo "    echo '📋 Copying latest code to GitHub Desktop...'"
echo "    rsync -av --delete --exclude='.git' --exclude='node_modules' \\"
echo "          /Users/davidniewiadomski/owners-cockpit/ \\"
echo "          $DESKTOP_FOLDER/"
echo "    echo '✅ Code copied! Open GitHub Desktop and push.'"
echo "}"
echo ""
echo "# Save this function to your shell profile"
echo "echo 'copy_to_github_desktop() {' >> ~/.zshrc"
echo "echo '    rsync -av --delete --exclude=\".git\" --exclude=\"node_modules\" \\' >> ~/.zshrc"
echo "echo '          /Users/davidniewiadomski/owners-cockpit/ \\' >> ~/.zshrc"
echo "echo '          $DESKTOP_FOLDER/' >> ~/.zshrc"
echo "echo '    echo \"✅ Code synced to GitHub Desktop!\"' >> ~/.zshrc"
echo "echo '}' >> ~/.zshrc"
echo ""
echo "🎉 After setup:"
echo "   1. I make code updates"
echo "   2. You run: copy_to_github_desktop"
echo "   3. You open GitHub Desktop and click 'Push'"
echo "   4. Lovable automatically syncs!"
echo ""
echo "🚀 This creates the perfect continuous deployment workflow!"
