-- Sample data for Performance Scorecards
-- This seed data creates sample KPI data for testing the performance scorecard functionality

-- Insert sample performance KPIs for different companies and periods
INSERT INTO performance_kpi (company_id, project_id, metric, value, period, source, notes) VALUES
-- Metropolitan Steel Works (Q3-2024)
((SELECT id FROM companies WHERE name = 'Metropolitan Steel Works' LIMIT 1), 
 (SELECT id FROM projects WHERE name LIKE '%Tower%' LIMIT 1), 
 'quality_score', 92.5, 'Q3-2024', 'Quality Inspection Reports', 'Excellent workmanship on structural elements'),
((SELECT id FROM companies WHERE name = 'Metropolitan Steel Works' LIMIT 1), 
 (SELECT id FROM projects WHERE name LIKE '%Tower%' LIMIT 1), 
 'on_time_delivery', 96.2, 'Q3-2024', 'Project Management System', 'Consistently meeting deadlines'),
((SELECT id FROM companies WHERE name = 'Metropolitan Steel Works' LIMIT 1), 
 (SELECT id FROM projects WHERE name LIKE '%Tower%' LIMIT 1), 
 'budget_adherence', 98.1, 'Q3-2024', 'Financial Reports', 'Under budget by 1.9%'),
((SELECT id FROM companies WHERE name = 'Metropolitan Steel Works' LIMIT 1), 
 (SELECT id FROM projects WHERE name LIKE '%Tower%' LIMIT 1), 
 'safety_incidents', 0, 'Q3-2024', 'Safety Reports', 'No incidents reported'),
((SELECT id FROM companies WHERE name = 'Metropolitan Steel Works' LIMIT 1), 
 (SELECT id FROM projects WHERE name LIKE '%Tower%' LIMIT 1), 
 'customer_satisfaction', 4.8, 'Q3-2024', 'Customer Survey', 'High satisfaction rating'),

-- Premier Concrete Co. (Q3-2024)
((SELECT id FROM companies WHERE name = 'Premier Concrete Co.' LIMIT 1), 
 (SELECT id FROM projects WHERE name LIKE '%Tower%' LIMIT 1), 
 'quality_score', 94.8, 'Q3-2024', 'Quality Inspection Reports', 'Superior concrete quality'),
((SELECT id FROM companies WHERE name = 'Premier Concrete Co.' LIMIT 1), 
 (SELECT id FROM projects WHERE name LIKE '%Tower%' LIMIT 1), 
 'on_time_delivery', 98.5, 'Q3-2024', 'Project Management System', 'Excellent schedule adherence'),
((SELECT id FROM companies WHERE name = 'Premier Concrete Co.' LIMIT 1), 
 (SELECT id FROM projects WHERE name LIKE '%Tower%' LIMIT 1), 
 'budget_adherence', 97.3, 'Q3-2024', 'Financial Reports', 'Slightly over budget'),
((SELECT id FROM companies WHERE name = 'Premier Concrete Co.' LIMIT 1), 
 (SELECT id FROM projects WHERE name LIKE '%Tower%' LIMIT 1), 
 'safety_incidents', 1, 'Q3-2024', 'Safety Reports', 'Minor incident, quickly resolved'),
((SELECT id FROM companies WHERE name = 'Premier Concrete Co.' LIMIT 1), 
 (SELECT id FROM projects WHERE name LIKE '%Tower%' LIMIT 1), 
 'customer_satisfaction', 4.9, 'Q3-2024', 'Customer Survey', 'Exceptional service'),

-- Advanced MEP Solutions (Q3-2024)
((SELECT id FROM companies WHERE name = 'Advanced MEP Solutions' LIMIT 1), 
 (SELECT id FROM projects WHERE name LIKE '%Tower%' LIMIT 1), 
 'quality_score', 89.2, 'Q3-2024', 'Quality Inspection Reports', 'Good quality with minor issues'),
((SELECT id FROM companies WHERE name = 'Advanced MEP Solutions' LIMIT 1), 
 (SELECT id FROM projects WHERE name LIKE '%Tower%' LIMIT 1), 
 'on_time_delivery', 87.4, 'Q3-2024', 'Project Management System', 'Some delays in installation'),
((SELECT id FROM companies WHERE name = 'Advanced MEP Solutions' LIMIT 1), 
 (SELECT id FROM projects WHERE name LIKE '%Tower%' LIMIT 1), 
 'budget_adherence', 92.6, 'Q3-2024', 'Financial Reports', 'Over budget due to scope changes'),
((SELECT id FROM companies WHERE name = 'Advanced MEP Solutions' LIMIT 1), 
 (SELECT id FROM projects WHERE name LIKE '%Tower%' LIMIT 1), 
 'safety_incidents', 2, 'Q3-2024', 'Safety Reports', 'Two minor electrical incidents'),
((SELECT id FROM companies WHERE name = 'Advanced MEP Solutions' LIMIT 1), 
 (SELECT id FROM projects WHERE name LIKE '%Tower%' LIMIT 1), 
 'customer_satisfaction', 4.2, 'Q3-2024', 'Customer Survey', 'Satisfactory but needs improvement'),

-- Glass Tech Systems (Q3-2024)
((SELECT id FROM companies WHERE name = 'Glass Tech Systems' LIMIT 1), 
 (SELECT id FROM projects WHERE name LIKE '%Tower%' LIMIT 1), 
 'quality_score', 91.7, 'Q3-2024', 'Quality Inspection Reports', 'High-quality glazing work'),
((SELECT id FROM companies WHERE name = 'Glass Tech Systems' LIMIT 1), 
 (SELECT id FROM projects WHERE name LIKE '%Tower%' LIMIT 1), 
 'on_time_delivery', 93.8, 'Q3-2024', 'Project Management System', 'Generally on schedule'),
((SELECT id FROM companies WHERE name = 'Glass Tech Systems' LIMIT 1), 
 (SELECT id FROM projects WHERE name LIKE '%Tower%' LIMIT 1), 
 'budget_adherence', 95.4, 'Q3-2024', 'Financial Reports', 'Within acceptable budget variance'),
((SELECT id FROM companies WHERE name = 'Glass Tech Systems' LIMIT 1), 
 (SELECT id FROM projects WHERE name LIKE '%Tower%' LIMIT 1), 
 'safety_incidents', 0, 'Q3-2024', 'Safety Reports', 'No incidents reported'),
((SELECT id FROM companies WHERE name = 'Glass Tech Systems' LIMIT 1), 
 (SELECT id FROM projects WHERE name LIKE '%Tower%' LIMIT 1), 
 'customer_satisfaction', 4.5, 'Q3-2024', 'Customer Survey', 'Good satisfaction rating'),

-- Q2-2024 data for trend analysis
-- Metropolitan Steel Works (Q2-2024)
((SELECT id FROM companies WHERE name = 'Metropolitan Steel Works' LIMIT 1), 
 (SELECT id FROM projects WHERE name LIKE '%Tower%' LIMIT 1), 
 'quality_score', 90.2, 'Q2-2024', 'Quality Inspection Reports', 'Good quality, improving'),
((SELECT id FROM companies WHERE name = 'Metropolitan Steel Works' LIMIT 1), 
 (SELECT id FROM projects WHERE name LIKE '%Tower%' LIMIT 1), 
 'on_time_delivery', 94.1, 'Q2-2024', 'Project Management System', 'On schedule'),
((SELECT id FROM companies WHERE name = 'Metropolitan Steel Works' LIMIT 1), 
 (SELECT id FROM projects WHERE name LIKE '%Tower%' LIMIT 1), 
 'budget_adherence', 96.8, 'Q2-2024', 'Financial Reports', 'Within budget'),
((SELECT id FROM companies WHERE name = 'Metropolitan Steel Works' LIMIT 1), 
 (SELECT id FROM projects WHERE name LIKE '%Tower%' LIMIT 1), 
 'safety_incidents', 1, 'Q2-2024', 'Safety Reports', 'One minor incident'),
((SELECT id FROM companies WHERE name = 'Metropolitan Steel Works' LIMIT 1), 
 (SELECT id FROM projects WHERE name LIKE '%Tower%' LIMIT 1), 
 'customer_satisfaction', 4.6, 'Q2-2024', 'Customer Survey', 'Good satisfaction'),

-- Premier Concrete Co. (Q2-2024)
((SELECT id FROM companies WHERE name = 'Premier Concrete Co.' LIMIT 1), 
 (SELECT id FROM projects WHERE name LIKE '%Tower%' LIMIT 1), 
 'quality_score', 93.1, 'Q2-2024', 'Quality Inspection Reports', 'Consistent quality'),
((SELECT id FROM companies WHERE name = 'Premier Concrete Co.' LIMIT 1), 
 (SELECT id FROM projects WHERE name LIKE '%Tower%' LIMIT 1), 
 'on_time_delivery', 97.2, 'Q2-2024', 'Project Management System', 'Excellent timing'),
((SELECT id FROM companies WHERE name = 'Premier Concrete Co.' LIMIT 1), 
 (SELECT id FROM projects WHERE name LIKE '%Tower%' LIMIT 1), 
 'budget_adherence', 98.9, 'Q2-2024', 'Financial Reports', 'Under budget'),
((SELECT id FROM companies WHERE name = 'Premier Concrete Co.' LIMIT 1), 
 (SELECT id FROM projects WHERE name LIKE '%Tower%' LIMIT 1), 
 'safety_incidents', 0, 'Q2-2024', 'Safety Reports', 'No incidents'),
((SELECT id FROM companies WHERE name = 'Premier Concrete Co.' LIMIT 1), 
 (SELECT id FROM projects WHERE name LIKE '%Tower%' LIMIT 1), 
 'customer_satisfaction', 4.8, 'Q2-2024', 'Customer Survey', 'High satisfaction'),

-- Additional metrics for companies
-- Response time metrics
((SELECT id FROM companies WHERE name = 'Metropolitan Steel Works' LIMIT 1), 
 (SELECT id FROM projects WHERE name LIKE '%Tower%' LIMIT 1), 
 'response_time', 4.2, 'Q3-2024', 'Issue Tracking System', 'Average 4.2 hours response time'),
((SELECT id FROM companies WHERE name = 'Premier Concrete Co.' LIMIT 1), 
 (SELECT id FROM projects WHERE name LIKE '%Tower%' LIMIT 1), 
 'response_time', 2.8, 'Q3-2024', 'Issue Tracking System', 'Quick response to issues'),
((SELECT id FROM companies WHERE name = 'Advanced MEP Solutions' LIMIT 1), 
 (SELECT id FROM projects WHERE name LIKE '%Tower%' LIMIT 1), 
 'response_time', 6.5, 'Q3-2024', 'Issue Tracking System', 'Slower response times'),
((SELECT id FROM companies WHERE name = 'Glass Tech Systems' LIMIT 1), 
 (SELECT id FROM projects WHERE name LIKE '%Tower%' LIMIT 1), 
 'response_time', 3.9, 'Q3-2024', 'Issue Tracking System', 'Good response time'),

-- Change order rates
((SELECT id FROM companies WHERE name = 'Metropolitan Steel Works' LIMIT 1), 
 (SELECT id FROM projects WHERE name LIKE '%Tower%' LIMIT 1), 
 'change_order_rate', 8.3, 'Q3-2024', 'Contract Management', 'Low change order rate'),
((SELECT id FROM companies WHERE name = 'Premier Concrete Co.' LIMIT 1), 
 (SELECT id FROM projects WHERE name LIKE '%Tower%' LIMIT 1), 
 'change_order_rate', 5.1, 'Q3-2024', 'Contract Management', 'Very low change orders'),
((SELECT id FROM companies WHERE name = 'Advanced MEP Solutions' LIMIT 1), 
 (SELECT id FROM projects WHERE name LIKE '%Tower%' LIMIT 1), 
 'change_order_rate', 15.2, 'Q3-2024', 'Contract Management', 'Higher change order rate'),
((SELECT id FROM companies WHERE name = 'Glass Tech Systems' LIMIT 1), 
 (SELECT id FROM projects WHERE name LIKE '%Tower%' LIMIT 1), 
 'change_order_rate', 9.7, 'Q3-2024', 'Contract Management', 'Moderate change orders'),

-- Defect rates
((SELECT id FROM companies WHERE name = 'Metropolitan Steel Works' LIMIT 1), 
 (SELECT id FROM projects WHERE name LIKE '%Tower%' LIMIT 1), 
 'defect_rate', 2.1, 'Q3-2024', 'Quality Control', 'Low defect rate'),
((SELECT id FROM companies WHERE name = 'Premier Concrete Co.' LIMIT 1), 
 (SELECT id FROM projects WHERE name LIKE '%Tower%' LIMIT 1), 
 'defect_rate', 1.3, 'Q3-2024', 'Quality Control', 'Excellent quality control'),
((SELECT id FROM companies WHERE name = 'Advanced MEP Solutions' LIMIT 1), 
 (SELECT id FROM projects WHERE name LIKE '%Tower%' LIMIT 1), 
 'defect_rate', 4.8, 'Q3-2024', 'Quality Control', 'Higher defect rate needs attention'),
((SELECT id FROM companies WHERE name = 'Glass Tech Systems' LIMIT 1), 
 (SELECT id FROM projects WHERE name LIKE '%Tower%' LIMIT 1), 
 'defect_rate', 2.9, 'Q3-2024', 'Quality Control', 'Acceptable defect rate')

ON CONFLICT (company_id, project_id, metric, period) DO UPDATE SET
  value = EXCLUDED.value,
  source = EXCLUDED.source,
  notes = EXCLUDED.notes,
  updated_at = NOW();
