-- Temporary migration to disable RLS for demo purposes
-- This allows the dashboard to display data without authentication

-- Disable RLS on core tables
ALTER TABLE projects DISABLE ROW LEVEL SECURITY;
ALTER TABLE tasks DISABLE ROW LEVEL SECURITY;
ALTER TABLE budget_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE budget_breakdown DISABLE ROW LEVEL SECURITY;
ALTER TABLE action_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE documents DISABLE ROW LEVEL SECURITY;
ALTER TABLE images DISABLE ROW LEVEL SECURITY;
ALTER TABLE vector_index DISABLE ROW LEVEL SECURITY;
ALTER TABLE rfi DISABLE ROW LEVEL SECURITY;
ALTER TABLE project_insights DISABLE ROW LEVEL SECURITY;
ALTER TABLE preconstruction_metrics DISABLE ROW LEVEL SECURITY;
ALTER TABLE project_kpis DISABLE ROW LEVEL SECURITY;
ALTER TABLE contractor_bids DISABLE ROW LEVEL SECURITY;
ALTER TABLE permit_status DISABLE ROW LEVEL SECURITY;
ALTER TABLE project_team DISABLE ROW LEVEL SECURITY;
ALTER TABLE capture_sets DISABLE ROW LEVEL SECURITY;
ALTER TABLE bim_files DISABLE ROW LEVEL SECURITY;
ALTER TABLE project_integrations DISABLE ROW LEVEL SECURITY;
ALTER TABLE construction_activities DISABLE ROW LEVEL SECURITY;
ALTER TABLE project_design_metrics DISABLE ROW LEVEL SECURITY;
ALTER TABLE project_facilities_metrics DISABLE ROW LEVEL SECURITY;
ALTER TABLE project_legal_metrics DISABLE ROW LEVEL SECURITY;

-- Note: To re-enable RLS after demo, run:
-- ALTER TABLE [table_name] ENABLE ROW LEVEL SECURITY;
