// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqdwxbxofiadcvaeexjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxZHd4YnhvZmlhZGN2YWVleGpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NTExNDksImV4cCI6MjA2NjIyNzE0OX0.yabfg_m0EeooU0OCkOra-HAWyHJQ7vcF9hJeCyE1s30";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);